version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - insight_net
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - insight_net
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: insightstream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - insight_net

networks:
  insight_net:

volumes:
  postgres_data: