name: Deploy to EC2 on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_INSIGHTSTREAM }}
          username: ${{ secrets.EC2_USER_INSIGHTSTREAM }}
          key: ${{ secrets.EC2_SSH_KEY_INSIGHTSTREAM }}
          script: |
            if [ ! -d "insightstream" ]; then
              git clone https://github.com/zeusthegoat/insightstream.git
            fi
            cd insightstream
            git pull origin main
            docker compose build
            docker compose up -d