name: Deploy to EC2 on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy updated services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_INSIGHTSTREAM }}
          username: ${{ secrets.EC2_USER_INSIGHTSTREAM }}
          key: ${{ secrets.EC2_SSH_KEY_INSIGHTSTREAM }}
          script: |
            cd insightstream
            echo "Pulling latest changes..."
            git pull origin main

            echo "Rebuilding backend and frontend only..."
            docker compose build backend frontend

            echo "Restarting backend and frontend without affecting db..."
            docker compose up -d --no-deps backend frontend

            echo "✅ Deployment complete."